Build options
Becksteinlab/streaming-md-docker pull request #11
Opened 2024-10-19 21:24 UTC by ljwoods2

Fixes #10 

Make GPU and MPI options available for simulation engines, but also create "vanilla" build for simple use in CI testing

2024-10-20 23:41 UTC, hmacdope requested changes
I think this is a good idea to split them up for now, however we will likely still need a container with all three engines installed for tutorial / demos, where people will want to run with all three engines.

Similar for CI, will we want to pull in 3 different containers or only one? I'm not sure, open question. 

 Perhaps adding another directory with `common` that builds all three will solve that?

2024-10-20 23:41 UTC, hmacdope commented on docker/lammps/env.yaml
> +
Whitespace changes

2024-10-20 23:41 UTC, hmacdope commented on docker/namd/env.yaml
> +
Whitespace changes

2024-10-21 22:33 UTC, ljwoods2 commented
Fair enough, my thinking is that for actual use after the workshop but before we actually merge this code into an i.e. gromacs release, people would want to have a container with just the simulation engine they want to use rather than a massive one. Though it makes sense to me to have one demo/test container where we dump everything

2024-10-22 09:30 UTC, hmacdope commented
@ljwoods2 

>  I can create a "common" one. Should this have all the different GPU/threading options as well? Or just GPU and nothing else?

For common I would do one common all GPU and one common all CPU with our most useful config for each (no MPI)

2024-10-25 22:43 UTC, ljwoods2 commented
@hmacdope Didn't end up doing a multi-stage build since this would've required installing another nearly-identical conda environment into the second stage without gcc, cmake, cudatools, etc (all the build specific dependencies) which felt redundant. This should be a "good enough" solution that makes the containers lighter by a few GB.

2024-10-26 23:52 UTC, ljwoods2 commented
Going to merge and test this, made a backup of main on "archive" branch in case we need to hard reset for some reason

2024-10-26 23:52 UTC, merged